/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2025 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "core/Compatibility.h"
#include "erofs/ErofsSuperBlock.h"

#include <gtest/gtest.h>

#include <random>

#include <fcntl.h>
#include <unistd.h>

using namespace ::testing;
using namespace entos::ralf::erofs;

TEST(TestErofsSuperBlock, basicParsing)
{
    uint8_t block[4096] = {};

    {
        auto *superPtr = reinterpret_cast<ErofsSuperBlockStruct *>(block + EROFS_SUPER_OFFSET);
        superPtr->magic = EROFS_MAGIC;
        superPtr->featureCompat = ErofsCompatFeature::ModificationTime;
        superPtr->blockSizeBits = 12;
        superPtr->extensionSlots = 0;
        superPtr->rootInode = 123;
        superPtr->inodeCount = 234;
        superPtr->buildTimeSec = 1768325570;
        superPtr->buildTimeNSec = 1234;
        superPtr->blocks = 56;
        superPtr->metaBlockAddr = 12;
        superPtr->xattrBlockAddr = 2;
        superPtr->featureIncompat = ErofsIncompatFeature::ZeroPadding;
    }

    auto sb = ErofsSuperBlock::parse(block, sizeof(block));
    ASSERT_TRUE(sb.has_value());

    EXPECT_EQ(sb->rootInode(), ino_t(123));
    EXPECT_EQ(sb->blockSize(), size_t(4096));
    EXPECT_EQ(sb->inodeOffset(9876), size_t((12 * 4096) + (9876 * 32)));

    EXPECT_TRUE(sb->hasFeature(ErofsSuperBlock::Feature::ZeroPadding));
    EXPECT_FALSE(sb->hasFeature(ErofsSuperBlock::Feature::SuperBlockChecksum));
    EXPECT_TRUE(sb->hasFeature(ErofsSuperBlock::Feature::ModificationTime));
    EXPECT_FALSE(sb->hasFeature(ErofsSuperBlock::Feature::XattrFilter));

    EXPECT_EQ(sb->buildTime().tv_sec, 1768325570);
    EXPECT_EQ(sb->buildTime().tv_nsec, 1234);
}

TEST(TestErofsSuperBlock, missingMagic)
{
    uint8_t block[4096] = {};

    {
        auto *superPtr = reinterpret_cast<ErofsSuperBlockStruct *>(block + EROFS_SUPER_OFFSET);
        superPtr->magic = EROFS_MAGIC + 1;
        superPtr->featureCompat = ErofsCompatFeature::ModificationTime;
        superPtr->blockSizeBits = 12;
        superPtr->extensionSlots = 0;
        superPtr->rootInode = 123;
        superPtr->inodeCount = 234;
        superPtr->buildTimeSec = time(nullptr);
        superPtr->buildTimeNSec = 0;
        superPtr->blocks = 56;
        superPtr->metaBlockAddr = 12;
        superPtr->xattrBlockAddr = 2;
        superPtr->featureIncompat = ErofsIncompatFeature::ZeroPadding;
    }

    auto sb = ErofsSuperBlock::parse(block, sizeof(block));
    ASSERT_FALSE(sb.has_value());
}

TEST(TestErofsSuperBlock, incompatibleFeatures)
{
    uint8_t block[4096] = {};

    {
        auto *superPtr = reinterpret_cast<ErofsSuperBlockStruct *>(block + EROFS_SUPER_OFFSET);
        superPtr->magic = EROFS_MAGIC;
        superPtr->featureCompat = ErofsCompatFeature::ModificationTime;
        superPtr->blockSizeBits = 12;
        superPtr->extensionSlots = 0;
        superPtr->rootInode = 123;
        superPtr->inodeCount = 234;
        superPtr->buildTimeSec = time(nullptr);
        superPtr->buildTimeNSec = 0;
        superPtr->blocks = 56;
        superPtr->metaBlockAddr = 12;
        superPtr->xattrBlockAddr = 2;
        superPtr->featureIncompat = ErofsIncompatFeature::ZeroPadding | ErofsIncompatFeature::BigPcluster;
    }

    auto sb = ErofsSuperBlock::parse(block, sizeof(block));
    ASSERT_FALSE(sb.has_value());
}

TEST(TestErofsSuperBlock, superBlockChecksum)
{
    uint8_t block[4096];

    // Read data/empty.erofs.im which was generated by the mkfs.erofs tool
    {
        int fd = open(TEST_DATA_DIR "/erofs_1.img", O_CLOEXEC | O_RDONLY);
        ASSERT_GE(fd, 0);

        ssize_t rd = TEMP_FAILURE_RETRY(read(fd, block, sizeof(block)));
        ASSERT_EQ(rd, static_cast<ssize_t>(sizeof(block)));

        close(fd);
    }

    // Parse the superblock and ensure the checksum crc was set
    auto sb = ErofsSuperBlock::parse(block, sizeof(block));
    ASSERT_FALSE(sb.isError()) << "failed to parse superblock: " << sb.error().what();

    EXPECT_TRUE(sb->hasFeature(ErofsSuperBlock::Feature::ZeroPadding));
    EXPECT_TRUE(sb->hasFeature(ErofsSuperBlock::Feature::SuperBlockChecksum));
    EXPECT_TRUE(sb->hasFeature(ErofsSuperBlock::Feature::ModificationTime));
    EXPECT_FALSE(sb->hasFeature(ErofsSuperBlock::Feature::XattrFilter));

    // Corrupt a random byte and check if fails verification
    std::random_device rd;
    block[EROFS_SUPER_OFFSET + (rd() % 512)] ^= 0x40;

    sb = ErofsSuperBlock::parse(block, sizeof(block));
    ASSERT_FALSE(sb.has_value());
}
