/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2025 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include "ArchiveReader.h"
#include "core/CryptoDigestBuilder.h"
#include "core/IPackageEntryImpl.h"

#include <memory>

namespace entos::ralf::archive
{

    // -------------------------------------------------------------------------
    /*!
        \class ArchiveBaseEntry
        \brief A base class for entries within an archive.


    */
    class ArchiveBaseEntry : public LIBRALF_NS::IPackageEntryImpl
    {
    public:
        ArchiveBaseEntry(std::filesystem::path &&path, std::filesystem::file_type type, size_t size,
                         std::filesystem::perms perms, time_t modTime, uid_t uid, gid_t gid)
            : m_path(std::move(path))
            , m_type(type)
            , m_size(size)
            , m_perms(perms)
            , m_modTime(modTime)
            , m_uid(uid)
            , m_gid(gid)
        {
        }

        ~ArchiveBaseEntry() override = default;

        const std::filesystem::path &path() const override { return m_path; }

        size_t size() const override { return m_size; }

        std::filesystem::perms permissions() const override { return m_perms; }

        time_t modificationTime() const override { return m_modTime; }

        uid_t ownerId() const override { return m_uid; }

        gid_t groupId() const override { return m_gid; }

        std::filesystem::file_type type() const override { return m_type; }

        ssize_t read(void *_Nullable buf, size_t size, LIBRALF_NS::Error *_Nullable error) override { return -1; }

        LIBRALF_NS::Result<size_t> writeTo(int directoryFd, size_t maxSize,
                                           LIBRALF_NS::Package::ExtractOptions options) override
        {
            (void)directoryFd;
            (void)maxSize;
            (void)options;

            return LIBRALF_NS::Error(LIBRALF_NS::ErrorCode::NotSupported);
        }

    protected:
        const std::filesystem::path m_path;
        const std::filesystem::file_type m_type;
        const size_t m_size;
        const std::filesystem::perms m_perms;
        const time_t m_modTime;
        const uid_t m_uid;
        const gid_t m_gid;
    };

    // -------------------------------------------------------------------------
    /*!
        \class ArchiveDirectoryEntry
        \brief An entry that represents a directory in an archive.

        These objects just store the path to the directory and the directory meta
        data.

     */
    class ArchiveDirectoryEntry final : public ArchiveBaseEntry
    {
    public:
        static std::unique_ptr<ArchiveDirectoryEntry> create(std::filesystem::path path, time_t modTime);
        static std::unique_ptr<ArchiveDirectoryEntry> create(const std::filesystem::path::iterator &pathBegin,
                                                             const std::filesystem::path::iterator &pathEnd,
                                                             time_t modTime);

    public:
        ArchiveDirectoryEntry(std::filesystem::path &&path, time_t modTime);
        ~ArchiveDirectoryEntry() final = default;

        ssize_t read(void *_Nullable buf, size_t size, LIBRALF_NS::Error *_Nullable error) final;

        LIBRALF_NS::Result<size_t> writeTo(int directoryFd, size_t maxSize,
                                           LIBRALF_NS::Package::ExtractOptions options) final;
    };

    // -------------------------------------------------------------------------
    /*!
        \class ArchiveSymlinkEntry
        \brief An entry that represents a symlink in an archive.

        These objects just store the symlink target string and the symlink meta
        data.  The symlink target is verified against a sha256 hash if supplied.

        \note Current widgets generated by the sky signer strips out symlinks
        as the zip format didn't traditionally support them.  However they are
        included here in case they are needed in the future.
     */
    class ArchiveSymlinkEntry final : public ArchiveBaseEntry
    {
    public:
        static std::unique_ptr<ArchiveSymlinkEntry>
        create(const std::shared_ptr<ArchiveReader::SharedReadState> &readState, std::filesystem::path path,
               const char *_Nullable target, time_t modTime, const std::optional<std::vector<uint8_t>> &digest);

    public:
        ArchiveSymlinkEntry(std::filesystem::path &&path, std::string &&target, time_t modTime);
        ~ArchiveSymlinkEntry() final = default;

        ssize_t read(void *_Nullable buf, size_t size, LIBRALF_NS::Error *_Nullable error) final;

        LIBRALF_NS::Result<size_t> writeTo(int directoryFd, size_t maxSize,
                                           LIBRALF_NS::Package::ExtractOptions options) final;

    private:
        const std::string m_target;
        size_t m_offset;
    };

    // -------------------------------------------------------------------------
    /*!
        \class ArchiveFileEntry
        \brief An entry that represents a regular file in an achive.

        These objects store the path to the file, the file digest if supplied, the
     */
    class ArchiveFileEntry final : public ArchiveBaseEntry
    {
    public:
        static std::unique_ptr<ArchiveFileEntry> create(const std::shared_ptr<ArchiveReader::SharedReadState> &readState,
                                                        std::filesystem::path path, int64_t size, bool executable,
                                                        time_t modTime,
                                                        const std::optional<std::vector<uint8_t>> &digest);

    public:
        ArchiveFileEntry(const std::shared_ptr<ArchiveReader::SharedReadState> &readState, std::filesystem::path &&path,
                         size_t size, bool executable, time_t modTime, std::optional<std::vector<uint8_t>> digest);
        ~ArchiveFileEntry() final = default;

        ssize_t read(void *_Nullable buf, size_t size, LIBRALF_NS::Error *_Nullable error) final;

        LIBRALF_NS::Result<size_t> writeTo(int directoryFd, size_t maxSize,
                                           LIBRALF_NS::Package::ExtractOptions options) final;

    private:
        std::shared_ptr<ArchiveReader::SharedReadState> checkReadState(LIBRALF_NS::Error *_Nullable error);

        LIBRALF_NS::Result<size_t> doFileWrite(int fd, size_t maxSize, const std::unique_ptr<ILibarchiveReader> &archive);

    private:
        const std::weak_ptr<ArchiveReader::SharedReadState> m_readState;
        const std::optional<std::vector<uint8_t>> m_digest;
        const uint64_t m_index;

        std::unique_ptr<LIBRALF_NS::CryptoDigestBuilder> m_digestBuilder;
        bool m_eof;
    };

} // namespace entos::ralf::archive