/*
 * If not stated otherwise in this file or this component's LICENSE file the
 * following copyright and licenses apply:
 *
 * Copyright 2025 Comcast Cable Communications Management, LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

// -------------------------------------------------------------------------
/*!
    \defgroup EntosUrns
    \brief URN definitions for Entos platform.

    These are the vendor specific URNs that are used in the EntertainmentOS
    platform, they are typically used in package meta-data.

    \{
*/

// -------------------------------------------------------------------------
/*!
    ENTOS_AS_ACCESS_LEVEL1_PERMISSION
    ENTOS_AS_ACCESS_LEVEL2_PERMISSION
    ENTOS_AS_ACCESS_LEVEL3_PERMISSION
    ENTOS_AS_ACCESS_LEVEL4_PERMISSION
    ENTOS_AS_ACCESS_LEVEL5_PERMISSION

    The app or service is requesting access to the AS services with the given
    level.  Only one of these privileges will be set at any given time.

    In practical terms this means the app or service can access AS on one
    of its specified ports.
 */
#define ENTOS_AS_ACCESS_LEVEL1_PERMISSION "urn:entos:permission:as-access:level1"
#define ENTOS_AS_ACCESS_LEVEL2_PERMISSION "urn:entos:permission:as-access:level2"
#define ENTOS_AS_ACCESS_LEVEL3_PERMISSION "urn:entos:permission:as-access:level3"
#define ENTOS_AS_ACCESS_LEVEL4_PERMISSION "urn:entos:permission:as-access:level4"
#define ENTOS_AS_ACCESS_LEVEL5_PERMISSION "urn:entos:permission:as-access:level5"

// -------------------------------------------------------------------------
/*!
    The app or service is permitted to post intents to other apps or services
    via the AS system.
 */
#define ENTOS_AS_POST_INTENT_PERMISSION "urn:entos:permission:as-access:post-intents"

// -------------------------------------------------------------------------
/*!
    The application requires access to the ASPlayer composition API.  This
    allows the app to control playback of A/V content generated by the ASPlayer.

    \note This privilege is only available on platforms that support the ASPlayer.
    And is considered a legacy requirement, going forward expect all video
    surfaces to be handled in a more generic way.

    \note THis doesn't control access to the ASPlayer REST API, this is
    controlled by the \c ASAccessLevelX privileges.
 */
#define ENTOS_AS_PLAYER_PERMISSION "urn:entos:permission:as-player"

// -------------------------------------------------------------------------
/*!
    The application requires access to AirPlay services.
 */
#define ENTOS_AIRPLAY_PERMISSION "urn:entos:permission:airplay"

// -------------------------------------------------------------------------
/*!
    The application requires access to Chrome Cast services.
 */
#define ENTOS_CHROMECAST_PERMISSION "urn:entos:permission:chromecast"

// -------------------------------------------------------------------------
/*!
    The application requires the ability to request a bearer token from
    the system for authentication to backend systems.
 */
#define ENTOS_BEARER_TOKEN_AUTHENTICATION_PERMISSION "urn:entos:permission:bearer-token-authentication"

// -------------------------------------------------------------------------
/*!
    The application requires the ability to access mTLS certificates
    for authentication to backend systems.

 */
#define ENTOS_HTTPS_MTLS_AUTHENTICATION_PERMISSION "urn:entos:permission:https-mutual-authentication"

// -------------------------------------------------------------------------
/*!
    The application requires access to information on the current entitlements
    set on the device.

    This does not give the app access to modify the entitlements, just to
    read the current entitlement information.
 */
#define ENTOS_ENTITLEMENT_INFO_PERMISSION "urn:entos:permission:entitlements:info"

// -------------------------------------------------------------------------
/*!
    \deprecated

    Use TIME_SHIFT_BUFFER_PERMISSION instead.  This is kept for backwards compatibility.
 */
#define ENTOS_TIME_SHIFT_BUFFER_PERMISSION "urn:entos:permission:timeshiftbuffer"

// -------------------------------------------------------------------------
/*!
    \deprecated

    Legacy permission used to denote special behaviour if the app was launched.
    This is no longer used, but kept for backwards compatibility.
 */
#define ENTOS_MEMORY_INTENSIVE_PERMISSION "urn:entos:permission:memory-intensive"

// -------------------------------------------------------------------------
/*!
    \deprecated

    The platform filters for the package.  These are not used on the device
    but are used by some legacy services to determine if the package is
    suitable for a given platform.

    The configuration is an object with fields for each type of filter, for
    example:
        \code{.json}
        {
            "platformIds": [ "SCXI11AIC", ... ]
            "platformVariants": [ "RDK-STB", ...]
            "propositions": [ "SKYQGW", ...]
            "countries":  [ "NZL", ...]
            "subdivisions": [ "GB-SCT", ...]
            "yoctoVersions": [ "KIRKSTONE", ...]
        }
        \endcode

 */
#define ENTOS_PLATFORM_FILTERS_CONFIGURATION "urn:entos:config:platform:filters"

// -------------------------------------------------------------------------
/*!
    The app or service requires access to the Mediarite API (MAPI).

    This configuration should contain an object like the following:
        \code{.json}
        {
            "underlay": true / false
            "accessGroups": {
                <groupName>: [ <default>, <trusted>, <core> ]
            }
        }
        \endcode
 */
#define ENTOS_MEDIARITE_CONFIGURATION "urn:entos:config:mediarite"

// -------------------------------------------------------------------------
/*!
    \deprecated

    This configuration is deprecated and should not be used.  It was used
    to denote that an app required access to the Sky Live system device.
 */
#define ENTOS_SKY_LIVE_CONFIGURATION "urn:entos:config:sky-live"

// -------------------------------------------------------------------------
/*!
    The pin management configuration for the app or service. The configuration
    contains a string that can be one of the following values:
        - "readwrite" - the app or service can read and write the pin
        - "readonly" - the app or service can only read the pin
        - "excluded" - the app or service is excluded from pin management
 */
#define ENTOS_PIN_MANAGEMENT_CONFIGURATION "urn:entos:config:pin-management"

// -------------------------------------------------------------------------
/*!
    The pre-launch configuration for the app.  Configuration should contain
    a string with one of the following values:
        - "allowed" - may be pre-launched even if the app has never been launched
        - "recent" - app may be pre-launched if it has been launched recently
        - "never" - the app should never be pre-launched
 */
#define ENTOS_PRELAUNCH_CONFIGURATION "urn:entos:config:prelaunch"

// -------------------------------------------------------------------------
/*!
    The age rating for the app.  The configuration should contain a single
    integer value that represents the age rating.

 */
#define ENTOS_AGE_RATING_CONFIGURATION "urn:entos:config:age-rating"

// -------------------------------------------------------------------------
/*!
    The age policy configuration for the app, the configuration should contain
    a single string describing the policy.

 */
#define ENTOS_AGE_POLICY_CONFIGURATION "urn:entos:config:age-policy"

// -------------------------------------------------------------------------
/*!
    \deprecated

    The content partner id for the app.  The configuration should contain a
    single string that represents the catalogue id.

*/
#define ENTOS_CONTENT_PARTNER_ID_CONFIGURATION "urn:entos:config:content-partner-id"

// -------------------------------------------------------------------------
/*!
    \deprecated

    The catalogue id for the app.  The configuration should contain a single
    string that represents the catalogue id.
*/
#define ENTOS_CATALOGUE_ID_CONFIGURATION "urn:entos:config:catalogue-id"

// -------------------------------------------------------------------------
/*!
    Defines the the list of FKPS files to be mapped into the container.
    The configuration should contain an array of strings, each string is
    a path to a FKPS file that should be mapped into the container.

        \code{.json}
           {
               "files": [
                    "file1.fkps",
                    "file2.fkps",
                   ...
               ]
           }
        \endcode

*/
#define ENTOS_FKPS_CONFIGURATION "urn:entos:config:fkps"

// -------------------------------------------------------------------------
/*!
    \deprecated

    Keep for backwards compatibility, but hasn't been used for a long time.
    The configuration should contain a boolean value to indicate parental control
    is enabled or not.  The absence of this configuration means parental control
    is not enabled.
*/
#define ENTOS_PARENTAL_CONTROL_CONFIGURATION "urn:entos:config:parental-control"

// -------------------------------------------------------------------------
/*!
    The app or service requires some sort of access to multicast sockets.

    This configuration should contain an object like the following:
        \code{.json}
            {
                "forwarding": [
                    {
                        "address": "<multicast address>",
                        "port": <port number>,
                    }, ...
                ]
                "serverSockets": [
                    {
                        "port": <port number>,
                        "address": "<multicast address>",
                        "name": <name of the socket>
                    }, ...
                ],
                "clientSockets": [
                    {
                        "name": <name of the socket>
                    }, ...
                ]
            }
        \endcode
*/
#define ENTOS_MULTICAST_CONFIGURATION "urn:entos:config:multicast"

// -------------------------------------------------------------------------
/*!
    \deprecated

    Describes the legacy DRM configuration for the app.  This configuration
    will contain a object formatted like the following:

        \code{.json}
        {
            "types": [ "com.widevine.alpha", "org.w3.clearkey" ],
            "storageSizeKB": 3000
        }
        \endcode
 */
#define ENTOS_LEGACY_DRM_CONFIGURATION "urn:entos:config:legacy:drm"

// -------------------------------------------------------------------------
/*!
    Icon configuration was not included in the original spec, but is used
    to define the icon configuration for the app or service.

    Note that the config follows the web manifest icon specification,
    \see https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Manifest/Reference/icons.

    This configuration should contain an object like the following:
    \code{.json}
        [
            {
                "src": "icon/low-res.png",
                "sizes": "48x48",
                "type": "image/png",
            },
            {
                "src": "icon/high-res.png",
                "sizes": "192x192"
            },
            {
                "src": "maskable_icon.png",
                "sizes": "48x48",
                "type": "image/png"
            }
        ]
    \endcode
 */
#define ENTOS_ICONS_CONFIGURATION "urn:entos:config:icons"

// -------------------------------------------------------------------------
/*!
    Describes the display modes and configuration for the app.  This configuration
    will contain an object formatted like the following:

    \code{.json}
        {
            "refreshRateHz": "default" | "60Hz" | "120Hz" | "144Hz" | "240Hz",
            "pictureMode": "<name of picture mode>",
        }
    \endcode
 */
#define ENTOS_DISPLAY_CONFIGURATION "urn:entos:config:display"

// -------------------------------------------------------------------------
/*!
    Describes the audio configuration requested for the app.  This configuration
    will contain an object formatted like the following:

    \code{.json}
        {
            "soundMode": "<name of sound mode>",
            "soundScene": "<name of sound scene>",
            "loudnessAdjustment": <integer value in dB>
        }
    \endcode
 */
#define ENTOS_AUDIO_CONFIGURATION "urn:entos:config:audio"

// -------------------------------------------------------------------------
/*!
    This is a rarely used config used to inform the system that the app
    should be terminated prior to the app entering a low power state.

    The config should contain a boolean value, \c true if the app should be
    terminated prior to the device entering a low power state.

    If the config is not present then it defaults to false.
*/
#define ENTOS_LOW_POWER_TERMINATE_CONFIGURATION "urn:entos:config:low-power:terminate"

// -------------------------------------------------------------------------
/*!
    The app must show marketplace intercept screen on launch.

    \code{.json}
        "configure": {
            "urn:entos:config:marketplace-intercept": {
                "enable": true
            }
        }
     \endcode
*/
#define ENTOS_MARKETPLACE_INTERCEPT_CONFIGURATION "urn:entos:config:marketplace-intercept"

// -------------------------------------------------------------------------
/*!
    The media type for the EntOS appsecrets "auxiliary meta-data" file.

 */
#define ENTOS_APPSECRETS_MEDIATYPE "application/vnd.entos.package.content.layer.appsecrets.v1+json"

// -------------------------------------------------------------------------
/*!
    \}

    End of the EntOS specific URNs.
*/
